<?xml version = "v1.0" ?>
<robot name="robo" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find robo_description)/urdf/robo_macro.xacro" />

    <base />
    <wheel prefix="left" ref="1" />
    <wheel prefix="right" ref="-1" />

    <caster prefix="front" ref="1" />
    <caster prefix="back" ref="-1" />
    
    <head_camera />
    <!--<head_kinect />-->
    <rplidar />

    <gazebo>
        <plugin name="differential_drive_controller" 
                filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>true</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <legacyMode>true</legacyMode>
            <leftJoint>left_wheel_joint</leftJoint>
            <rightJoint>right_wheel_joint</rightJoint>
            <wheelSeparation>${base_radius*2}</wheelSeparation>
            <wheelDiameter>${2*wheel_radius}</wheelDiameter>
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic>
            <odometryFrame>odom</odometryFrame> 
            <odometryTopic>odom</odometryTopic> 
            <robotBaseFrame>base_link</robotBaseFrame>
        </plugin>
    </gazebo>
    
</robot>